services:
  app:
    build: .
    ports:
      - "8001:8000"
    environment:
      - NODE_ENV=development
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_NAME=bitespeed
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_SSL=false
    restart: unless-stopped
